---
language: python
python: 2.7
cache: pip
sudo: required

services:
  - docker

before_install:
  - curl -sSL "https://ftp-master.debian.org/keys/archive-key-7.0.asc" | sudo -E apt-key add -
  - echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list > /dev/null
  - sudo apt-get install shellcheck=0.3.3-1~ubuntu14.04.1
  - pip install -U -r test-requirements.txt

install: true

before_script:
  - "./tests/test-shellcheck.sh"
  - "./tests/test-yamllint.sh"

script: "./tests/test-minikube.sh"
